/**
 * Material Symbols — Google's modern Material Icons.
 *
 * One variable font powers every icon. Four axes control appearance:
 *   - FILL:   0 (outline) → 1 (filled)
 *   - wght:   100 → 700 (thickness)
 *   - GRAD:   -25 → 200 (emphasis)
 *   - opsz:   20 → 48 (optical size)
 *
 * Three style variants are available: Outlined, Rounded, Sharp.
 *
 * To use an icon, render its *ligature name* as text inside a span with
 * the appropriate font-family. See the Icon component for a typed wrapper.
 */

export type IconVariant = "outlined" | "rounded" | "sharp";

export const iconVariants: IconVariant[] = ["outlined", "rounded", "sharp"];

export const iconVariantLabel: Record<IconVariant, string> = {
  outlined: "Outlined",
  rounded: "Rounded",
  sharp: "Sharp",
};

export const iconFontFamily: Record<IconVariant, string> = {
  outlined: "Material Symbols Outlined",
  rounded: "Material Symbols Rounded",
  sharp: "Material Symbols Sharp",
};

export type IconCategory =
  | "Navigation"
  | "Actions"
  | "Content"
  | "Communication"
  | "Media"
  | "Files"
  | "Data"
  | "Toggles"
  | "User"
  | "Commerce"
  | "Alerts"
  | "Devices"
  | "Editor"
  | "Social"
  | "Maps"
  | "Weather"
  | "Misc";

/**
 * A curated, searchable registry of ~500 commonly used Material Symbols,
 * grouped by category. Any icon name from fonts.google.com/icons will render
 * correctly — this list exists for browsing; the Playground accepts any name.
 */
export const iconRegistry: Record<IconCategory, string[]> = {
  Navigation: [
    "home",
    "menu",
    "close",
    "arrow_back",
    "arrow_forward",
    "arrow_upward",
    "arrow_downward",
    "arrow_drop_down",
    "arrow_drop_up",
    "chevron_left",
    "chevron_right",
    "expand_more",
    "expand_less",
    "unfold_more",
    "unfold_less",
    "first_page",
    "last_page",
    "keyboard_arrow_left",
    "keyboard_arrow_right",
    "more_vert",
    "more_horiz",
    "apps",
    "dashboard",
    "grid_view",
    "view_list",
    "view_module",
    "view_agenda",
    "open_in_new",
    "open_in_full",
    "close_fullscreen",
    "fullscreen",
    "fullscreen_exit",
    "subdirectory_arrow_right",
    "swap_horiz",
    "swap_vert",
  ],
  Actions: [
    "search",
    "settings",
    "tune",
    "filter_list",
    "filter_alt",
    "sort",
    "add",
    "add_circle",
    "remove",
    "remove_circle",
    "edit",
    "edit_note",
    "delete",
    "delete_outline",
    "clear",
    "cancel",
    "check",
    "check_circle",
    "done",
    "done_all",
    "save",
    "save_as",
    "print",
    "share",
    "download",
    "upload",
    "cloud_download",
    "cloud_upload",
    "refresh",
    "sync",
    "cached",
    "restore",
    "undo",
    "redo",
    "copy_all",
    "content_copy",
    "content_cut",
    "content_paste",
    "drag_indicator",
    "drag_handle",
    "open_with",
    "link",
    "link_off",
    "visibility",
    "visibility_off",
    "lock",
    "lock_open",
    "key",
    "fingerprint",
    "login",
    "logout",
    "power_settings_new",
    "touch_app",
  ],
  Content: [
    "add_box",
    "remove_circle_outline",
    "create",
    "archive",
    "unarchive",
    "reply",
    "reply_all",
    "forward",
    "redo",
    "undo",
    "flag",
    "bookmark",
    "bookmark_border",
    "bookmarks",
    "push_pin",
    "star",
    "star_border",
    "star_half",
    "grade",
    "favorite",
    "favorite_border",
    "thumb_up",
    "thumb_down",
    "emoji_emotions",
    "format_list_bulleted",
    "format_list_numbered",
    "format_quote",
    "checklist",
    "fact_check",
    "rule",
  ],
  Communication: [
    "mail",
    "mail_outline",
    "drafts",
    "inbox",
    "send",
    "chat",
    "chat_bubble",
    "chat_bubble_outline",
    "forum",
    "message",
    "sms",
    "phone",
    "phone_in_talk",
    "call",
    "call_end",
    "call_made",
    "call_received",
    "call_missed",
    "voicemail",
    "contacts",
    "contact_mail",
    "contact_phone",
    "person_add",
    "group",
    "group_add",
    "groups",
    "mark_email_read",
    "mark_email_unread",
    "outgoing_mail",
    "notifications",
    "notifications_active",
    "notifications_off",
    "notifications_none",
    "notifications_paused",
  ],
  Media: [
    "play_arrow",
    "pause",
    "stop",
    "skip_next",
    "skip_previous",
    "fast_forward",
    "fast_rewind",
    "replay",
    "shuffle",
    "repeat",
    "repeat_one",
    "volume_up",
    "volume_down",
    "volume_mute",
    "volume_off",
    "mic",
    "mic_off",
    "mic_none",
    "headphones",
    "speaker",
    "music_note",
    "library_music",
    "queue_music",
    "radio",
    "album",
    "audiotrack",
    "video_library",
    "videocam",
    "videocam_off",
    "movie",
    "live_tv",
    "smart_display",
    "cast",
    "cast_connected",
    "slow_motion_video",
    "subtitles",
    "closed_caption",
    "playlist_add",
    "playlist_play",
    "equalizer",
    "graphic_eq",
  ],
  Files: [
    "folder",
    "folder_open",
    "folder_shared",
    "create_new_folder",
    "drive_folder_upload",
    "description",
    "article",
    "file_copy",
    "insert_drive_file",
    "text_snippet",
    "picture_as_pdf",
    "image",
    "photo",
    "photo_library",
    "collections",
    "attach_file",
    "attachment",
    "cloud",
    "cloud_queue",
    "cloud_done",
    "cloud_off",
    "cloud_sync",
    "backup",
    "storage",
    "folder_zip",
    "snippet_folder",
    "upload_file",
    "download_for_offline",
    "topic",
  ],
  Data: [
    "analytics",
    "assessment",
    "bar_chart",
    "pie_chart",
    "show_chart",
    "stacked_bar_chart",
    "stacked_line_chart",
    "trending_up",
    "trending_down",
    "trending_flat",
    "leaderboard",
    "insights",
    "query_stats",
    "data_thresholding",
    "scatter_plot",
    "bubble_chart",
    "timeline",
    "schedule",
    "history",
    "table_chart",
    "table_rows",
    "table_view",
    "list",
    "list_alt",
    "grid_on",
    "grid_off",
    "functions",
    "calculate",
    "percent",
  ],
  Toggles: [
    "toggle_on",
    "toggle_off",
    "check_box",
    "check_box_outline_blank",
    "indeterminate_check_box",
    "radio_button_checked",
    "radio_button_unchecked",
    "star_rate",
    "heart_plus",
    "switch_left",
    "switch_right",
  ],
  User: [
    "person",
    "person_outline",
    "account_circle",
    "account_box",
    "manage_accounts",
    "supervisor_account",
    "assignment_ind",
    "badge",
    "co_present",
    "portrait",
    "face",
    "perm_identity",
    "how_to_reg",
    "psychology",
    "emoji_people",
    "self_improvement",
    "verified",
    "verified_user",
    "security",
    "shield",
    "gpp_good",
    "gpp_bad",
    "admin_panel_settings",
  ],
  Commerce: [
    "shopping_cart",
    "shopping_bag",
    "shopping_basket",
    "store",
    "storefront",
    "local_mall",
    "local_offer",
    "sell",
    "loyalty",
    "card_giftcard",
    "redeem",
    "payments",
    "payment",
    "credit_card",
    "account_balance",
    "account_balance_wallet",
    "attach_money",
    "money",
    "paid",
    "receipt",
    "receipt_long",
    "point_of_sale",
    "request_quote",
    "qr_code",
    "qr_code_2",
    "barcode_reader",
  ],
  Alerts: [
    "info",
    "help",
    "help_outline",
    "warning",
    "warning_amber",
    "error",
    "error_outline",
    "report",
    "report_problem",
    "dangerous",
    "priority_high",
    "new_releases",
    "announcement",
    "campaign",
    "feedback",
    "support",
    "support_agent",
    "contact_support",
    "crisis_alert",
    "emergency",
    "pending",
    "pending_actions",
    "hourglass_top",
    "hourglass_bottom",
  ],
  Devices: [
    "phone_android",
    "phone_iphone",
    "tablet",
    "tablet_mac",
    "laptop",
    "laptop_mac",
    "laptop_windows",
    "desktop_windows",
    "desktop_mac",
    "computer",
    "tv",
    "watch",
    "speaker_group",
    "cast_for_education",
    "keyboard",
    "mouse",
    "print",
    "scanner",
    "router",
    "memory",
    "sim_card",
    "sd_card",
    "battery_full",
    "battery_charging_full",
    "battery_alert",
    "bluetooth",
    "bluetooth_connected",
    "wifi",
    "wifi_off",
    "signal_cellular_alt",
    "usb",
  ],
  Editor: [
    "format_bold",
    "format_italic",
    "format_underlined",
    "format_strikethrough",
    "format_align_left",
    "format_align_center",
    "format_align_right",
    "format_align_justify",
    "format_indent_increase",
    "format_indent_decrease",
    "format_color_fill",
    "format_color_text",
    "format_clear",
    "format_size",
    "format_h1",
    "format_h2",
    "title",
    "spellcheck",
    "text_fields",
    "text_format",
    "strikethrough_s",
    "subscript",
    "superscript",
    "code",
    "terminal",
    "data_object",
    "integration_instructions",
  ],
  Social: [
    "public",
    "language",
    "group_work",
    "diversity_3",
    "waving_hand",
    "celebration",
    "cake",
    "handshake",
    "mood",
    "mood_bad",
    "sentiment_satisfied",
    "sentiment_dissatisfied",
    "sentiment_very_satisfied",
    "sentiment_very_dissatisfied",
    "share_location",
    "share",
  ],
  Maps: [
    "place",
    "location_on",
    "location_off",
    "my_location",
    "explore",
    "explore_off",
    "map",
    "near_me",
    "directions",
    "directions_car",
    "directions_walk",
    "directions_bike",
    "directions_bus",
    "directions_train",
    "directions_boat",
    "flight",
    "local_taxi",
    "traffic",
    "local_gas_station",
    "local_parking",
    "restaurant",
    "local_cafe",
    "local_bar",
    "local_grocery_store",
    "local_hospital",
    "local_pharmacy",
    "hotel",
    "school",
    "work",
  ],
  Weather: [
    "sunny",
    "clear_day",
    "partly_cloudy_day",
    "cloud",
    "cloudy",
    "rainy",
    "thunderstorm",
    "severe_cold",
    "snowing",
    "ac_unit",
    "thermostat",
    "water_drop",
    "air",
    "storm",
    "beach_access",
    "wb_sunny",
    "nights_stay",
    "bedtime",
  ],
  Misc: [
    "calendar_today",
    "calendar_month",
    "event",
    "event_available",
    "today",
    "schedule",
    "alarm",
    "alarm_on",
    "timer",
    "hourglass_empty",
    "date_range",
    "pets",
    "restaurant_menu",
    "nature",
    "park",
    "eco",
    "recycling",
    "psychiatry",
    "medication",
    "health_and_safety",
    "monitor_heart",
    "fitness_center",
    "sports_esports",
    "sports_soccer",
    "sports",
    "toys",
    "child_care",
    "palette",
    "brush",
    "draw",
    "auto_awesome",
    "magic_button",
    "extension",
    "widgets",
    "view_in_ar",
    "qr_code_scanner",
    "barcode",
  ],
};

export const iconCategories = Object.keys(iconRegistry) as IconCategory[];

/** Flat array of every icon name in the registry. */
export const allIcons: string[] = iconCategories.flatMap(
  (c) => iconRegistry[c]
);

/** Total count (unique names). */
export const iconCount = new Set(allIcons).size;

/**
 * Build the font-variation-settings string for Material Symbols axes.
 */
export const buildIconVariation = (opts: {
  fill?: 0 | 1;
  weight?: number;
  grade?: number;
  opticalSize?: number;
}): string => {
  const fill = opts.fill ?? 0;
  const wght = opts.weight ?? 400;
  const grad = opts.grade ?? 0;
  const opsz = opts.opticalSize ?? 24;
  return `'FILL' ${fill}, 'wght' ${wght}, 'GRAD' ${grad}, 'opsz' ${opsz}`;
};
